function [fitresult, gof] = curve(T_cal, R_cal)
%CREATEFIT(T_CAL,R_CAL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : T_cal
%      Y Output: R_cal
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jun-2023 18:17:06


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( T_cal, R_cal );

% Set up fittype and options.
ft = fittype( 'R0*exp(B*(1/(273.15+x)- 1/298.15))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.655098003973841 0.162611735194631];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'R_cal vs. T_cal', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel T_cal
ylabel R_cal
grid on


